# Generated by Django 4.0.1 on 2022-03-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_alter_profile_url_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='url_img',
            field=models.ImageField(blank=True, default='/assets/img-profile/Jirafita.png', null=True, upload_to='assets/img-profile'),
        ),
    ]
